---
title: "QFISH"
author: "Payton Schlewitt"
date: "2024-05-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("tidyverse") #Only run once
#install.packages("usethis")  #Only run once
library("tidyverse")
library("usethis")
```

```{r}
use_git_config(user.name = "payschlew34", user.email = "pschlewitt@gmail.com")
#if on a new device, generate a new personal access token
gitcreds::gitcreds_set()
```

#Data sourced from the State of Queensland, Department of Agriculture, Fisheries

#Allow R to access our csv file
```{r}
commercial_line <- read.csv("D:\\github.module\\MB5370_gitR_PaySchlew\\data\\QFISH_Commercial_Line.csv")
#refining data set to exclude total values and 2024 because the data is still incomplete for that year
comm_line_2023 <- commercial_line %>% filter(!row_number() %in% c(35, 36))
```
#Creating a basic line plot with Tonnes vs Year
```{r}
ggplot(data = comm_line_2023, mapping = aes(x = CalendarYear, y = Tonnes)) +
  geom_point() +
  geom_line(group = 1) +
  #geom_smooth() +
  scale_x_discrete(breaks = seq(1990, 2023, by = 2)) + 
  #scale_y_continuous(breaks = seq(1500, 6500, by = 500)) +
  labs(x = "Year")
```

#Trying other graphs for remaining variables
```{r}
ggplot(data = comm_line_2023, mapping = aes(x = CalendarYear, y = Licences)) +
  geom_point() +
  #geom_smooth() +
  geom_line(group = 1) +
  scale_x_discrete(breaks = seq(1990, 2023, by = 2)) +
  labs(x = "Year")
```

```{r}
#Days with catch reported (unsure of how this metric was calculated, source data not clear)
ggplot(data = comm_line_2023, mapping = aes(x = CalendarYear, y = Days)) +
  geom_point() +
  #geom_smooth() +
  geom_line(group = 1) +
  scale_x_discrete(breaks = seq(1990, 2023, by = 2)) +
  labs(x = "Year")
```
